package com.mycompany.cajero;

import java.awt.Color;
import java.util.List;
import java.math.BigDecimal;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author JoustinBergerMonge
 */
public class InicioSesion extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();

        Conexion connectionObject = new Conexion();
        connectionObject.establishConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        falla = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        passLabel = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        registerBtn = new javax.swing.JPanel();
        registerBtnLabel = new javax.swing.JLabel();
        loginBtn = new javax.swing.JPanel();
        loginBtnLabel = new javax.swing.JLabel();
        labelText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        falla.setBackground(new java.awt.Color(255, 255, 255));
        falla.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        falla.setForeground(new java.awt.Color(204, 204, 204));
        falla.setBorder(null);
        bg.add(falla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 20, 0));

        title.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("INICIAR SESIÓN");
        bg.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exit.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 0, 0));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 310, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 40));

        userLabel.setBackground(new java.awt.Color(255, 255, 255));
        userLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(0, 0, 0));
        userLabel.setText("USUARIO");
        bg.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 59, -1, -1));

        userTxt.setBackground(new java.awt.Color(255, 255, 255));
        userTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        userTxt.setForeground(new java.awt.Color(204, 204, 204));
        userTxt.setText("Ingrese el nombre de usuario");
        userTxt.setBorder(null);
        userTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userTxtFocusLost(evt);
            }
        });
        bg.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 330, -1));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 114, 330, 10));

        passLabel.setBackground(new java.awt.Color(255, 255, 255));
        passLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        passLabel.setForeground(new java.awt.Color(0, 0, 0));
        passLabel.setText("PIN");
        bg.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 142, -1, -1));

        passField.setBackground(new java.awt.Color(255, 255, 255));
        passField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passField.setForeground(new java.awt.Color(204, 204, 204));
        passField.setText("**********");
        passField.setBorder(null);
        passField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFieldFocusLost(evt);
            }
        });
        bg.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 175, 324, 20));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 195, 330, 10));

        registerBtn.setBackground(new java.awt.Color(0, 0, 0));
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));

        registerBtnLabel.setBackground(new java.awt.Color(255, 255, 255));
        registerBtnLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        registerBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerBtnLabel.setText("REGISTRAR");
        registerBtnLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBtnLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerBtnLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerBtnLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout registerBtnLayout = new javax.swing.GroupLayout(registerBtn);
        registerBtn.setLayout(registerBtnLayout);
        registerBtnLayout.setHorizontalGroup(
            registerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        registerBtnLayout.setVerticalGroup(
            registerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 40));

        loginBtn.setBackground(new java.awt.Color(0, 0, 0));

        loginBtnLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        loginBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtnLabel.setText("ENTRAR");
        loginBtnLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginBtnLayout = new javax.swing.GroupLayout(loginBtn);
        loginBtn.setLayout(loginBtnLayout);
        loginBtnLayout.setHorizontalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        loginBtnLayout.setVerticalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        labelText.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelText.setForeground(new java.awt.Color(153, 153, 153));
        labelText.setText("¿Aún no tienes cuenta? Dale click en REGISTRAR");
        bg.add(labelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 362, 329));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exitBtn.setBackground(Color.red);
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exitBtn.setBackground(Color.white);
        exit.setForeground(Color.black);

    }//GEN-LAST:event_exitMouseExited

    private void registerBtnLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnLabelMouseEntered
        registerBtn.setBackground(new Color(102, 102, 102));
        registerBtnLabel.setForeground(Color.black);
    }//GEN-LAST:event_registerBtnLabelMouseEntered

    private void registerBtnLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnLabelMouseExited
        registerBtn.setBackground(new Color(0, 0, 0));
        registerBtnLabel.setForeground(Color.white);

    }//GEN-LAST:event_registerBtnLabelMouseExited

    private void loginBtnLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnLabelMouseEntered
        loginBtn.setBackground(new Color(102, 102, 102));
        loginBtnLabel.setForeground(Color.black);    }//GEN-LAST:event_loginBtnLabelMouseEntered

    private void loginBtnLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnLabelMouseExited
        loginBtn.setBackground(new Color(0, 0, 0));
        loginBtnLabel.setForeground(Color.white);
    }//GEN-LAST:event_loginBtnLabelMouseExited

    private void userTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTxtFocusLost
        if (String.valueOf(passField.getPassword()).equals("**********")) {
            passField.setText("");
            passField.setForeground(Color.black);
        }
        if (userTxt.getText().isEmpty()) {
            userTxt.setText("Ingrese el nombre de usuario");
            userTxt.setForeground(Color.gray);
        }

    }//GEN-LAST:event_userTxtFocusLost

    private void passFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldFocusLost
        if (userTxt.getText().equals("Ingrese el nombre de usuario")) {
            userTxt.setText("");
            userTxt.setForeground(Color.black);
        }
        if (String.valueOf(passField.getPassword()).isEmpty()) {
            passField.setText("**********");
            passField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_passFieldFocusLost

    private void registerBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnLabelMouseClicked
        new Registro().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_registerBtnLabelMouseClicked

    private boolean isInvalidPin(String pin) {
        if (pin.isEmpty() || pin.equals("**********") || pin.length() != 4) {
            return true;
        }

        try {
            Integer.parseInt(pin);
        } catch (NumberFormatException e) {
            return true;
        }

        return false;
    }


    private void loginBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnLabelMouseClicked
        // LOGIN

        String username = userTxt.getText();
        String pin = String.valueOf(passField.getPassword());

        if (isInvalidPin(pin)) {
            JOptionPane.showMessageDialog(null, "El pin no está ingresado en un formato correcto");
        } else {
            int pinInt = Integer.parseInt(pin);

            Conexion connectionObject = new Conexion();

            String sql = "SELECT * FROM usuario WHERE username = ? and PIN = ?";
            String cuentaSql = "SELECT numero_cuenta, saldo FROM cuenta WHERE username = ?";

            try {

                PreparedStatement ps = connectionObject.establishConnection().prepareStatement(sql);
                ps.setString(1, username);
                ps.setInt(2, pinInt);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    String name = rs.getString("nombre");
                    String lastname = rs.getString("apellido");

                    PreparedStatement cuentaPs = connectionObject.establishConnection().prepareStatement(cuentaSql);
                    cuentaPs.setString(1, username);
                    ResultSet cuentaRs = cuentaPs.executeQuery();

                    List<Cuenta> accounts = new ArrayList<>();

                    while (cuentaRs.next()) {
                        long accountNumber = cuentaRs.getLong("numero_cuenta");
                        BigDecimal balance = cuentaRs.getBigDecimal("saldo");

                        Cuenta cuenta = new Cuenta(accountNumber, balance);
                        accounts.add(cuenta);
                    }

                    new Inicio(name, lastname, accounts, username, pinInt).setVisible(true);

                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Contraseña o usuario incorrectos. Verifica los datos e intenta de nuevo");
                }
            } catch (SQLException ex) {
                Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_loginBtnLabelMouseClicked

    private void userTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTxtFocusGained
        if (userTxt.getText().equals("Ingrese el nombre de usuario")) {
            userTxt.setText("");
            userTxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_userTxtFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JTextField falla;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelText;
    private javax.swing.JPanel loginBtn;
    private javax.swing.JLabel loginBtnLabel;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPanel registerBtn;
    private javax.swing.JLabel registerBtnLabel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
