/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cajero;

import java.awt.Color;
import java.math.BigDecimal;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JoustinBergerMonge
 */
public class Registro extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form Test
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        backBtn = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lastnameLabel = new javax.swing.JLabel();
        lastnameText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        usernameLabel = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        pinLabel = new javax.swing.JLabel();
        pinText = new javax.swing.JPasswordField();
        JSeparator5 = new javax.swing.JSeparator();
        cuentasLabel = new javax.swing.JLabel();
        cuentasText = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        createBtn = new javax.swing.JPanel();
        createLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(800, 200));
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        bg.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 10));

        title.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("REGISTRO DE USUARIO");
        bg.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exit.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 0, 0));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        header.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 40, 40));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));

        back.setFont(new java.awt.Font("Serif", 1, 26)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 0));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("⬅");
        back.setToolTipText("");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        javax.swing.GroupLayout backBtnLayout = new javax.swing.GroupLayout(backBtn);
        backBtn.setLayout(backBtnLayout);
        backBtnLayout.setHorizontalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        backBtnLayout.setVerticalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        header.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 40, 40));

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 50));

        nameLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 0, 0));
        nameLabel.setText("NOMBRE");
        bg.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        nameText.setBackground(new java.awt.Color(255, 255, 255));
        nameText.setForeground(new java.awt.Color(204, 204, 204));
        nameText.setText("Ingresa tu nombre");
        nameText.setBorder(null);
        nameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFocusLost(evt);
            }
        });
        bg.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 320, 30));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 350, 20));

        lastnameLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lastnameLabel.setForeground(new java.awt.Color(0, 0, 0));
        lastnameLabel.setText("APELLIDO");
        bg.add(lastnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lastnameText.setBackground(new java.awt.Color(255, 255, 255));
        lastnameText.setForeground(new java.awt.Color(204, 204, 204));
        lastnameText.setText("Ingresa tu apellido");
        lastnameText.setBorder(null);
        lastnameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameTextFocusLost(evt);
            }
        });
        lastnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTextActionPerformed(evt);
            }
        });
        bg.add(lastnameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 320, 30));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 350, 20));

        usernameLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        usernameLabel.setText("NOMBRE DE USUARIO");
        bg.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        usernameText.setBackground(new java.awt.Color(255, 255, 255));
        usernameText.setForeground(new java.awt.Color(204, 204, 204));
        usernameText.setText("Ingresa tu nombre de usuario");
        usernameText.setBorder(null);
        usernameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTextFocusLost(evt);
            }
        });
        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });
        bg.add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 320, 30));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 350, 20));

        pinLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        pinLabel.setForeground(new java.awt.Color(0, 0, 0));
        pinLabel.setText("PIN");
        bg.add(pinLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        pinText.setBackground(new java.awt.Color(255, 255, 255));
        pinText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pinText.setForeground(new java.awt.Color(204, 204, 204));
        pinText.setText("******");
        pinText.setToolTipText("El PIN debe contener 4 dígitos numéricos");
        pinText.setBorder(null);
        pinText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pinTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pinTextFocusLost(evt);
            }
        });
        bg.add(pinText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 320, -1));
        bg.add(JSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 350, 20));

        cuentasLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        cuentasLabel.setForeground(new java.awt.Color(0, 0, 0));
        cuentasLabel.setText("CUENTAS");
        bg.add(cuentasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        cuentasText.setBackground(new java.awt.Color(255, 255, 255));
        cuentasText.setForeground(new java.awt.Color(204, 204, 204));
        cuentasText.setText("Ingresa el número de cuentas a crear (máximo 3)");
        cuentasText.setBorder(null);
        cuentasText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cuentasTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cuentasTextFocusLost(evt);
            }
        });
        bg.add(cuentasText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 320, 30));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 350, 20));

        createBtn.setBackground(new java.awt.Color(0, 0, 0));

        createLabel.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        createLabel.setForeground(new java.awt.Color(255, 255, 255));
        createLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createLabel.setText("CREAR USUARIO");
        createLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout createBtnLayout = new javax.swing.GroupLayout(createBtn);
        createBtn.setLayout(createBtnLayout);
        createBtnLayout.setHorizontalGroup(
            createBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        createBtnLayout.setVerticalGroup(
            createBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exitBtn.setBackground(Color.red);
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exitBtn.setBackground(Color.white);
        exit.setForeground(Color.black);
    }//GEN-LAST:event_exitMouseExited

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new InicioSesion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        backBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        backBtn.setBackground(Color.white);
    }//GEN-LAST:event_backMouseExited

    private void createLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createLabelMouseEntered
        createBtn.setBackground(new Color(102, 102, 102));
        createLabel.setForeground(Color.black);
    }//GEN-LAST:event_createLabelMouseEntered

    private void createLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createLabelMouseExited
        createBtn.setBackground(new Color(0, 0, 0));
        createLabel.setForeground(Color.white);
    }//GEN-LAST:event_createLabelMouseExited

    private boolean isInvalidName(String name) {
        return name.isEmpty() || name.equals("Ingresa tu nombre");
    }

    private boolean isInvalidLastName(String lastName) {
        return lastName.isEmpty() || lastName.equals("Ingresa tu apellido");
    }

    private boolean isInvalidUsername(String username) {
        if (username.isEmpty() || username.equals("Ingresa tu nombre de usuario")) {
            return true;
        }
        Conexion connectionObject = new Conexion();

        String sql = "SELECT * FROM usuario WHERE username = ?";

        try {
            PreparedStatement ps = connectionObject.establishConnection().prepareStatement(sql);
            ps.setString(1, username);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                return true;
            }
        } catch (SQLException ex) {

            return true;
        }

        return false;
    }

    private boolean isInvalidPin(String pin) {
        if (pin.isEmpty() || pin.equals("******") || pin.length() != 4) {
            return true;
        }

        try {
            Integer.parseInt(pin);
        } catch (NumberFormatException e) {
            return true;
        }

        return false;
    }

    private boolean isInvalidAmountAccounts(String amountAccountsString) {
        if (amountAccountsString.isEmpty() || amountAccountsString.equals("Ingresa el número de cuentas a crear (máximo 3)")) {
            return true;
        }

        try {
            int amountAccounts = Integer.parseInt(amountAccountsString);
            if (amountAccounts > 3) {
                return true;
            }
        } catch (NumberFormatException e) {
            return true;
        }

        return false;
    }


    private void createLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createLabelMouseClicked
        String name = nameText.getText();
        String lastname = lastnameText.getText();
        String username = usernameText.getText();
        String pin = String.valueOf(pinText.getPassword());
        String amountAccountsString = cuentasText.getText();

        if (isInvalidName(name)) {
            JOptionPane.showMessageDialog(null, "Ingresa tu nombre adecuadamente");
        } else if (isInvalidLastName(lastname)) {
            JOptionPane.showMessageDialog(null, "Ingresa tu apellido adecuadamente");
        } else if (isInvalidUsername(username)) {
            JOptionPane.showMessageDialog(null, "Ingresa tu nombre de usuario adecuadamente. El nombre de usuario ya existe o aún no se ha ingresado un valor");
        } else if (isInvalidPin(pin)) {
            JOptionPane.showMessageDialog(null, "Ingresa el PIN adecuadamente (Máximo 4 dígitos numéricos)");
        } else if (isInvalidAmountAccounts(amountAccountsString)) {
            JOptionPane.showMessageDialog(null, "Ingresa un número válido de cuentas");
        } else {
            Usuario usuario = new Usuario("", "", "", 0, 0);

            usuario.createUser(nameText, lastnameText, usernameText, pinText, cuentasText);
            BigDecimal balance = new BigDecimal(0);

            Cuenta cuenta = new Cuenta(0, balance);

            for (int i = 0; i < Integer.parseInt(cuentasText.getText()); i++) {
                String accountNumberString = cuenta.createUniqueAccountNumber();

                long accountNumber = Long.parseLong(accountNumberString);
                cuenta.createAccount(accountNumber, balance, usernameText.getText());
            }

            JOptionPane.showMessageDialog(null, "SE CREO EL USUARIO Y LAS CUENTAS");
        }


    }//GEN-LAST:event_createLabelMouseClicked

    private void nameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFocusGained
        if (nameText.getText().equals("Ingresa tu nombre")) {
            nameText.setText("");
            nameText.setForeground(Color.black);
        }
    }//GEN-LAST:event_nameTextFocusGained

    private void nameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFocusLost
        if (nameText.getText().isEmpty()) {
            nameText.setText("Ingresa tu nombre");
            nameText.setForeground(Color.gray);
        }
    }//GEN-LAST:event_nameTextFocusLost

    private void lastnameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameTextFocusGained
        if (lastnameText.getText().equals("Ingresa tu apellido")) {
            lastnameText.setText("");
            lastnameText.setForeground(Color.black);
        }
    }//GEN-LAST:event_lastnameTextFocusGained

    private void lastnameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameTextFocusLost
        if (lastnameText.getText().isEmpty()) {
            lastnameText.setText("Ingresa tu apellido");
            lastnameText.setForeground(Color.gray);
        }
    }//GEN-LAST:event_lastnameTextFocusLost

    private void usernameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFocusGained
        if (usernameText.getText().equals("Ingresa tu nombre de usuario")) {
            usernameText.setText("");
            usernameText.setForeground(Color.black);
        }
    }//GEN-LAST:event_usernameTextFocusGained

    private void usernameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFocusLost
        if (usernameText.getText().isEmpty()) {
            usernameText.setText("Ingresa tu nombre de usuario");
            usernameText.setForeground(Color.gray);
        }
    }//GEN-LAST:event_usernameTextFocusLost

    private void pinTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pinTextFocusGained
        if (String.valueOf(pinText.getPassword()).equals("******")) {
            pinText.setText("");
            pinText.setForeground(Color.black);
        }
    }//GEN-LAST:event_pinTextFocusGained

    private void pinTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pinTextFocusLost
        if (String.valueOf(pinText.getPassword()).isEmpty()) {
            pinText.setText("******");
            pinText.setForeground(Color.gray);
        }
    }//GEN-LAST:event_pinTextFocusLost

    private void cuentasTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cuentasTextFocusGained
        if (cuentasText.getText().equals("Ingresa el número de cuentas a crear (máximo 3)")) {
            cuentasText.setText("");
            cuentasText.setForeground(Color.black);
        }
    }//GEN-LAST:event_cuentasTextFocusGained

    private void cuentasTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cuentasTextFocusLost
        if (cuentasText.getText().isEmpty()) {
            cuentasText.setText("Ingresa el número de cuentas a crear (máximo 3)");
            cuentasText.setForeground(Color.gray);
        }
    }//GEN-LAST:event_cuentasTextFocusLost

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextActionPerformed

    private void lastnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator JSeparator5;
    private javax.swing.JLabel back;
    private javax.swing.JPanel backBtn;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel createBtn;
    private javax.swing.JLabel createLabel;
    private javax.swing.JLabel cuentasLabel;
    private javax.swing.JTextField cuentasText;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField lastnameText;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel pinLabel;
    private javax.swing.JPasswordField pinText;
    private javax.swing.JLabel title;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
